#!/usr/bin/env python3
"""Regenerate JobPosting structured data in jobs.html from jobs.json.
Run this after editing jobs.json:  python3 build-job-schema.py
It rewrites the block between the JOBPOSTING-SCHEMA markers (idempotent).
"""
import json, re, html, os, pathlib, datetime

ROOT = pathlib.Path(__file__).parent
jobs = json.loads((ROOT / "jobs.json").read_text(encoding="utf-8"))

ORG = {"@type": "Organization", "name": "TecheVision",
       "sameAs": "https://techevision.com/",
       "logo": "https://techevision.com/assets/icon-512.png"}
EMP = {"full-time": "FULL_TIME", "part-time": "PART_TIME", "contract": "CONTRACTOR",
       "temporary": "TEMPORARY", "internship": "INTERN", "contractor": "CONTRACTOR"}

def desc_html(text):
    parts = [p.strip() for p in (text or "").split("\n") if p.strip()]
    out, bullets = [], []
    def flush():
        if bullets:
            out.append("<ul>" + "".join("<li>%s</li>" % html.escape(b.lstrip("•").strip()) for b in bullets) + "</ul>")
            bullets.clear()
    for p in parts:
        if p.startswith("•"):
            bullets.append(p)
        else:
            flush(); out.append("<p>%s</p>" % html.escape(p))
    flush()
    return "".join(out) or "<p>%s</p>" % html.escape(text or "")

def city_region(loc):
    base = loc.split("(")[0].strip().rstrip("-–—").strip()
    if "," in base:
        c, r = base.split(",", 1)
        return c.strip(), r.strip().split()[0][:2].upper()
    return base or "Ashburn", "VA"

blocks = []
for j in jobs:
    posted = j.get("posted", "")
    try:
        valid = (datetime.date.fromisoformat(posted) + datetime.timedelta(days=90)).isoformat()
    except Exception:
        valid = ""
    city, region = city_region(j.get("location", "Ashburn, VA"))
    obj = {
        "@context": "https://schema.org/",
        "@type": "JobPosting",
        "title": j["title"],
        "description": desc_html(j.get("description") or j.get("summary", "")),
        "identifier": {"@type": "PropertyValue", "name": "TecheVision", "value": j.get("id", "")},
        "datePosted": posted,
        "employmentType": EMP.get((j.get("type") or "").lower(), "FULL_TIME"),
        "hiringOrganization": ORG,
        "directApply": True,
        "jobLocation": {"@type": "Place", "address": {
            "@type": "PostalAddress", "addressLocality": city,
            "addressRegion": region, "addressCountry": "US"}},
    }
    if valid:
        obj["validThrough"] = valid
    if (j.get("mode") or "").lower() == "remote":
        obj["jobLocationType"] = "TELECOMMUTE"
        obj["applicantLocationRequirements"] = {"@type": "Country", "name": "US"}
    blocks.append('<script type="application/ld+json">\n' +
                  json.dumps(obj, indent=2, ensure_ascii=False) + '\n</script>')

payload = ("  <!-- JOBPOSTING-SCHEMA:START (auto-generated by build-job-schema.py — run it after editing jobs.json) -->\n  "
           + "\n  ".join(blocks) + "\n  <!-- JOBPOSTING-SCHEMA:END -->")

p = ROOT / "jobs.html"
src = p.read_text(encoding="utf-8")
pat = re.compile(r"[ \t]*<!-- JOBPOSTING-SCHEMA:START.*?JOBPOSTING-SCHEMA:END -->", re.S)
src = pat.sub(payload, src) if pat.search(src) else src.replace("</head>", payload + "\n</head>", 1)
p.write_text(src, encoding="utf-8")
print("OK: wrote %d JobPosting blocks into jobs.html" % len(blocks))
